name: "Tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup
        run: npm install --only=dev

      - name: Lint
        run: ./node_modules/.bin/eslint -c .eslintrc.json --ext .js --ext .jsx

      #- name: Prettier
      #  run: ./node_modules/.bin/prettier --check "*.js" --end-of-line lf

      - name: Version check
        run: if (node -pe "require('./package.json').version" == cat ./VERSION); then exit 0; else exit 1; fi
